home/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nikkiw_nutrition/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'home/index.html')

home/templates/home/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/static/home/images/tukibill.ico">

    <title>Nikki W Nutrition</title>

      {# Load CSS and JavaScript #}
      {% bootstrap_css %}
      {% bootstrap_javascript jquery='full' %}

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="/static/home/css/cover.css" />

  </head>

  <body>

    <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>

    <div class="cover-container d-flex w-100 p-3 mx-auto flex-column">
      <header class="masthead mb-auto">
        <div class="inner">
          <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link active" href="{% url 'home:index' %}">Home</a>
            <a class="nav-link" href="#about">About</a>
            <a class="nav-link" href="#contact">Contact</a>
          </nav>
        </div>
      </header>
    </div>

    <div class="parallax">
      <div class="caption">
        <span class="border">NIKKI W NUTRITION</span>
      </div>
    </div>

    <div style="color: white;background-color: #575759;text-align:center;padding:50px 80px;text-align: justify;">
      <a name="about"></a>
      <h3 style="text-align:center;">What you do</h3>
      <p>Space to provide basic info</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet eros id nisi consequat finibus vel sit amet diam. Aliquam massa tortor, efficitur in elementum ac, dignissim eu lectus. Ut sollicitudin orci tempus, vehicula erat eu, sodales lectus. Curabitur finibus nisi sed magna interdum, eu sagittis elit vestibulum. Nam accumsan suscipit lacus. Vivamus eu tincidunt ante. Donec ornare, nunc at suscipit pulvinar, libero quam ullamcorper neque, non elementum nulla turpis malesuada turpis. Mauris ante quam, fermentum sed quam eu, elementum commodo enim. Phasellus suscipit et augue hendrerit laoreet. Donec et tincidunt turpis. Pellentesque mi ipsum, aliquam at velit a, sollicitudin varius lorem. Nulla eget neque finibus, imperdiet mauris sit amet, mattis elit.</p>
      <p>Donec non gravida mauris. Morbi placerat nulla vitae orci pellentesque, vitae consectetur nulla aliquam. Quisque eu sodales tellus, a ultricies sem. Vivamus id tellus pharetra, ornare diam eu, vehicula nisl. Aenean sed accumsan magna. Integer id nisl ac lorem pellentesque iaculis sed id lacus. Duis non congue mauris. In eget bibendum ex. Suspendisse consectetur vehicula ex nec facilisis. Fusce non dictum arcu. Curabitur in ullamcorper ante. Vivamus cursus dolor quis tortor tempor porttitor. Donec at gravida libero. Sed non nulla velit. Vestibulum et mattis risus. Etiam id diam enim.</p>
    </div>

    <div class="bgimg1"></div>

    <div style="position:relative;">
      <div style="color: white;background-color:#eb1a82;text-align:center;padding:50px 80px;text-align: justify;"></div>
    </div>

    <div class="parallax">
      <a name="contact"></a>
      <div class="caption">
        <span class="border" style="background-color:transparent;font-size:25px;color: #eb1a82;">Contact Info and links</span>
      </div>
    </div>

    <script src="/static/home/js/scroll2top.js"></script>

  </body>
</html>

home/templates/home/index.html
{% extends "home/base.html" %}
{% load bootstrap4 %}